<a href="https://colab.research.google.com/github/PrathamSapra/Numpy/blob/main/CompleteNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

In [1]:
import numpy as np


In [2]:
list = [1,3,4,5]
print(list)

[1, 3, 4, 5]


Advantages of Numpy Array over Lists

In [4]:
print('1D array')

a = np.array([1,2,3,4,5])
print(a)

print('2D Array')
b = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
print(b)

print('3D array')
c = np.array([[[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]]])
print(c)

1D array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [5]:
type(a)

numpy.ndarray

In [6]:
print(a.size)
print(b.size)
print(c.size)
# Tells the number of elements in the array

5
10
15


In [ ]:
# shape = (rows,cols)

print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [ ]:
# dtype  = Types of Data Present in the array

print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [ ]:
d = np.array([[1,2,3,4.20,5],
              [6.9,7,8,9,10],
              [11,12,13,14,15]])

print(d.dtype)

float64


In [ ]:
d.transpose()

# Inverts the rows and columns

array([[ 1. ,  6.9, 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8. , 13. ],
       [ 4.2,  9. , 14. ],
       [ 5. , 10. , 15. ]])

# Part 2

np.empty((row,cols), dtype)

In [11]:
np.empty((4,4), dtype = float)

array([[ 4.82508809e-310,  0.00000000e+000,  6.88782071e-310,
         6.88784179e-310],
       [-1.61915572e-046,  6.88782071e-310,  6.88784179e-310,
        -1.10274127e-011],
       [ 6.88782072e-310,  6.88784179e-310,  1.98920411e+154,
         6.88782068e-310],
       [ 6.88784179e-310,  1.44175929e-034,  6.88782071e-310,
         6.88784179e-310]])

np.ones((rows, cols),dtype)

In [13]:
x= np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [14]:
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
z = np.ones((3,5), dtype = int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

np.zeros((rows, cols),dtype)

In [16]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [18]:
y = np.zeros((4,8))
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
z = np.zeros((4,8), dtype = int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
z = np.zeros((4,8), dtype = str)
z

array([['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '']], dtype='<U1')

In [21]:
z = np.ones((4,8), dtype = bool)
z

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

# Part 3